"""Generate manuscript tables and figures only from recorded benchmark outputs."""
from pathlib import Path
from decimal import Decimal, ROUND_HALF_UP
import json, hashlib
import numpy as np
import pandas as pd
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
ROOT=Path(__file__).resolve().parents[1]
P=ROOT/'paper/journal'; O=P/'generated'; O.mkdir(exist_ok=True)
s=pd.read_csv(P/'results/simulation/summary.csv')
c=json.loads((P/'results/criteo/summary.json').read_text())
methods=['PROXIMA','Correlation','Decision only','Local only','Equal weights','No local component','Uniform proxy','Always ship','Never ship']
scenarios=['balanced','heterogeneous','noisy','shifted']
def val(scenario,method,metric):return s[(s.scenario==scenario)&(s.method==method)&(s.metric==metric)].iloc[0]
for metric in ['agreement','local_error','regret']:
    lines=['% Generated by scripts/build_journal_assets.py; do not edit.','\\begin{tabular}{lrrrr}','\\toprule','Method & Balanced & Heterog. & Noisy & Shifted \\\\','\\midrule']
    for method in methods:
        lines.append(method+' & '+' & '.join(str(Decimal(str(round(val(sc,method,metric)["mean"], 10))).quantize(Decimal('0.001'), rounding=ROUND_HALF_UP)) for sc in scenarios)+' \\\\')
    lines+=['\\bottomrule','\\end{tabular}']
    (O/f'{metric}.tex').write_text('\n'.join(lines)+'\n')
lines=['\\begin{tabular}{lr}','\\toprule','Quantity & Value \\\\','\\midrule']
for k,v in [('Analysis rows',f'{c["analysis_rows"]:,}'),('Random partitions',str(c['partitions'])),('Pearson correlation',f'{c["score"]["effect_corr"]:.3f}'),('Decision agreement',f'{c["score"]["directional_accuracy"]:.3f}'),('Local disagreement',f'{c["score"]["fragility_rate"]:.3f}'),('Composite score',f'{c["score"]["reliability"]:.3f}'),('Conditional 95\\% interval',f'[{c["conditional_partition_bootstrap_ci"][0]:.3f}, {c["conditional_partition_bootstrap_ci"][1]:.3f}]'),('Always-ship agreement',f'{c["always_ship"]["agreement"]:.3f}'),('Negative partitions',str(c["visit_decisions"]["fp"]+c["visit_decisions"]["tn"]))]:
    lines.append(f'{k} & {v} \\\\')
lines+=['\\bottomrule','\\end{tabular}'];(O/'criteo.tex').write_text('\n'.join(lines)+'\n')
plt.rcParams.update({'font.size':9,'axes.spines.top':False,'axes.spines.right':False,'pdf.fonttype':42})
fig,axes=plt.subplots(1,2,figsize=(7,2.9),layout='constrained')
colors=['#146b8f','#be6031','#5856a6','#358359']
for i,method in enumerate(['PROXIMA','Correlation','Decision only','Local only']):
    for ax,metric in zip(axes,['agreement','local_error']):
        rows=[val(sc,method,metric) for sc in scenarios];x=np.arange(4)+(i-1.5)*.16
        means=np.array([r['mean'] for r in rows]);err=np.array([r['ci_high']-r['mean'] for r in rows])
        ax.errorbar(x,means,yerr=err,fmt='o',markersize=4,capsize=2,color=colors[i],label=method)
        ax.set_xticks(range(4),['Balanced','Heterog.','Noisy','Shifted'],rotation=15)
        ax.grid(axis='y',alpha=.18)
axes[0].set_ylabel('Held-out decision agreement');axes[1].set_ylabel('Held-out local error')
axes[0].set_ylim(.45,1);axes[1].set_ylim(0,.55)
fig.legend(*axes[0].get_legend_handles_labels(),loc='outside upper center',ncols=4,frameon=False)
fig.savefig(O/'simulation.pdf');fig.savefig(O/'simulation.png',dpi=180);plt.close(fig)
paired=pd.read_csv(P/'results/simulation/paired_comparisons.csv')
lines=['\\begin{tabular}{lrr}','\\toprule','Scenario & Agreement difference & Local-error difference \\\\','\\midrule']
for sc in scenarios:
    cells=[]
    for metric in ['agreement','local_error']:
        row=paired[(paired.scenario==sc)&(paired.metric==metric)&(paired.comparator=='Correlation')].iloc[0]
        cells.append(f'{row.difference:+.3f} [{row.ci_low:+.3f}, {row.ci_high:+.3f}]')
    lines.append(sc.title()+' & '+' & '.join(cells)+' \\\\')
lines+=['\\bottomrule','\\end{tabular}'];(O/'paired.tex').write_text('\n'.join(lines)+'\n')
files=sorted((P/'results').rglob('*'))
manifest={str(f.relative_to(P)):hashlib.sha256(f.read_bytes()).hexdigest() for f in files if f.is_file()}
(P/'results-manifest.json').write_text(json.dumps(manifest,indent=2)+'\n')
print('Generated three benchmark tables, paired comparison, Criteo table and figure.')
